### ISSUE TITLE
Random crash subscribing to topics

### ISSUE THREAD

**Issue by brandonroth** [ckrey/MQTT-Client-Framework#113]
I've been experiencing a few random crashes while using the MQTTSessionManager to subscribe to a handful (57) topics at a time.  I'm creating my own dictionary and then assigning it to the `subscriptions` property.

When it does crash it happens in one of two ways.  The first on line 437 of MQTTSessionManager and the crash is `*** Collection <__NSDictionaryM: 0x7f8733cd13d0> was mutated while being enumerated.`. I initially though I may be mutating the subscriptions dictionary so I made a copy before changing it and then assigned it back but the issue persists.

The second is less obvious and it occurs on line 455 and that is an `EXEC BAD ACCESS` error.  I do have zombie objects enabled but that doesn't get triggered.

Both issues happen about 5% of the time.  I have crash reports if that would be helpful.

**Comment by mignick** [comment]
@ckrey 
I am looking into the same issue with EXEC BAD ACCESS that I have sometimes and  I think the reason for random crashes with EXEC BAD ACCESS could be a race in MQTTSessionManager when the lib is updating self.effectiveSubscriptions via callback handlers in subscribeTopic/unsubscribeTopic.
The callbacks are called on different threads and could change self.effectiveSubscriptions at the same time. It would be better to have a very special queue for these callbacks or just serialise the access to effectiveSubscriptions.

@brandonroth 
Unfortunately your PR do not fix EXEC BAD ACCESS crashes and it would be better to store self.effectiveSubscriptions keys in separate array which will be enumerated.

**Comment by AymanRadid** [comment]
@mignick 
Why do you propose to store the keys in an array? For better readability what I did seemed more clear. But we can change it, it fixes the problem either way though.

**Comment by brandonroth** [comment]
I'm not sure if this would fix the issue because the dictionary can still be mutated in the next if block.  I tried wrapping that function in an objc_sync_enter/objc_sync_exit block and it seems not to crash.  Then again race conditions are difficult to create so I'm not sure if that's the correct solution or not.

**Comment by mignick** [comment]
@ckrey 
Could you please tell us the status of this issue? I'm going to try to fix it if you are not fixing it right now.
I have an app in production and such crashes are the top ones.

```
Thread : Crashed: Thread
0  CoreFoundation                 0x1832c4c64 -[__NSDictionaryM setObject:forKey:] + 320
1  appname                        0x10029928c __47-[MQTTSessionManager connected:sessionPresent:]_block_invoke (MQTTSessionManager.m:396)
2  appname                        0x10029527c -[MQTTSession onSubscribeExecute:] (MQTTSession.m:1024)
3  Foundation                     0x183d9bc40 __NSThread__start__ + 1000
4  libsystem_pthread.dylib        0x183043b28 _pthread_body + 156
5  libsystem_pthread.dylib        0x183043a8c _pthread_body + 154
6  libsystem_pthread.dylib        0x183041028 thread_start + 4
```

```
Thread : Crashed: Thread
0  CoreFoundation                 0x1818d0c64 -[__NSDictionaryM setObject:forKey:] + 320
1  appname                        0x1002b1bdc __39-[MQTTSessionManager setSubscriptions:]_block_invoke221 (MQTTSessionManager.m:470)
2  appname                        0x1002ad27c -[MQTTSession onSubscribeExecute:] (MQTTSession.m:1024)
3  Foundation                     0x1823a7c40 __NSThread__start__ + 1000
4  libsystem_pthread.dylib        0x18164fb28 _pthread_body + 156
5  libsystem_pthread.dylib        0x18164fa8c _pthread_body + 154
6  libsystem_pthread.dylib        0x18164d028 thread_start + 4
```

Also, could you please clarify the purpose of the following line
 
> self.effectiveSubscriptions = self.effectiveSubscriptions;

that is almost every time when effectiveSubscriptions is modified? I do not get it.
Thanks.

**Comment by ckrey** [comment]
Assigning the effectiveSubscriptions to itself triggers any observers to be informed about a change in the object as described:

```
/** effectiveSubscriptions s a dictionary of NSNumber instances indicating the granted MQTTQoSLevel, or 0x80 for subscription failure.
 *  The keys are topic filters.
 *  effectiveSubscriptions is observable and is updated everytime subscriptions change
 *  @code
        ...
        MQTTSessionManager *manager = [[MQTTSessionManager alloc] init];
        manager.delegate = self;
 
        [manager addObserver:self
            forKeyPath:@"effectiveSubscriptions"
            options:NSKeyValueObservingOptionInitial | NSKeyValueObservingOptionNew
            context:nil];
            manager.subscriptions = [@{@"#": @(0)} mutableCopy];
            [manager connectTo: ...
        ...
        [manager removeObserver:self forKeyPath:@"effectiveSubscriptions"];
        ...
 
    - (void)observeValueForKeyPath:(NSString *)keyPath
        ofObject:(id)object
        change:(NSDictionary<NSString *,id> *)change
        context:(void *)context {
        if ([keyPath isEqualToString:@"effectiveSubscriptions"]) {
            MQTTSessionManager *manager = (MQTTSessionManager *)object;
            DDLogVerbose(@"effectiveSubscriptions changed: %@", manager.effectiveSubscriptions);
        }
    }
 *  @endcode
 */
@property (readonly, strong, nonatomic) NSDictionary<NSString *, NSNumber *> *effectiveSubscriptions;

```

**Comment by ckrey** [comment]
Crash problem solved by copying NSDictionary for enumeration and synchronizing access.

**Comment by mignick** [comment]
Thanks! Waiting for a new release :)

**Comment by xmkevin** [comment]
This issue is not fixed totally, Still have random crash, but I cannot repeat it.

**Comment by mignick** [comment]
+1 But I can't reproduce these crashes too

```
Crashed: Thread
0  libobjc.A.dylib                0x20f446d8 objc_release + 7
1  Barbara                        0x33410b __39-[MQTTSessionManager setSubscriptions:]_block_invoke.221 (MQTTSessionManager.m:484)
2  Barbara                        0x3300ff -[MQTTSession onSubscribeExecute:] (MQTTSession.m:1029)
3  Foundation                     0x21f9a62d __NSThread__start__ + 1144
4  libsystem_pthread.dylib        0x214a0c7f _pthread_body + 138
5  libsystem_pthread.dylib        0x214a0bf3 _pthread_start + 110
6  libsystem_pthread.dylib        0x2149ea08 thread_start + 8
```

```
Crashed: Thread
0  libobjc.A.dylib                0x22a846c8 objc_release + 7
1  Barbara                        0x35010b __39-[MQTTSessionManager setSubscriptions:]_block_invoke.221 (MQTTSessionManager.m:483)
2  Barbara                        0x34c0ff -[MQTTSession onSubscribeExecute:] (MQTTSession.m:1028)
3  Foundation                     0x23af9485 __NSThread__start__ + 1148
4  libsystem_pthread.dylib        0x2300385b _pthread_body + 138
5  libsystem_pthread.dylib        0x230037cf _pthread_start + 110
6  libsystem_pthread.dylib        0x23001724 thread_start + 8
```

```
Crashed: Thread
0  libobjc.A.dylib                0x22dcfa96 objc_msgSend + 21
1  Barbara                        0x3217a5 __47-[MQTTSessionManager connected:sessionPresent:]_block_invoke (MQTTSessionManager.m:401)
2  Barbara                        0x31e0ff -[MQTTSession onSubscribeExecute:] (MQTTSession.m:1028)
3  Foundation                     0x23e3262d __NSThread__start__ + 1144
4  libsystem_pthread.dylib        0x23338c7f _pthread_body + 138
5  libsystem_pthread.dylib        0x23338bf3 _pthread_start + 110
6  libsystem_pthread.dylib        0x23336a08 thread_start + 8
```

```
Crashed: Thread
0  libobjc.A.dylib                0x24ff06c8 objc_release + 7
1  Barbara                        0x2d77a5 __47-[MQTTSessionManager connected:sessionPresent:]_block_invoke (MQTTSessionManager.m:402)
2  Barbara                        0x2d40ff -[MQTTSession onSubscribeExecute:] (MQTTSession.m:1029)
3  Foundation                     0x26065485 __NSThread__start__ + 1148
4  libsystem_pthread.dylib        0x2556f85b _pthread_body + 138
5  libsystem_pthread.dylib        0x2556f7cf _pthread_start + 110
6  libsystem_pthread.dylib        0x2556d724 thread_start + 8
```
