### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by ThanhDev2703** [ckrey/MQTT-Client-Framework#27]
I read document and try use SSL. But I don't find way to use SSL cert and key.

**Comment by ckrey** [comment]
You just need to specifiy TLS when connecting. iOS' CFNetwork does the rest. it uses the highest negotiable TLS version, it verifies the servers' certificate. If you use self-signed server certificates, please install them in the iOS keystore by downloading them via https or mail.
MQTT-Flient does not support client-certificates (yet).

Does that answer your question?

**Comment by ThanhDev2703** [comment]
How to used my ssl certificate(cert and key) on iOS Project with your framework. Please help me.

**Comment by ckrey** [comment]
If you are talking about an MQTT broker/server certificate, you need to install this at the broker's site together with the matching key. Please refer to your broker documentation.

For the iOS client (iPhone, iPad or simulator), transfer the certificate file (typically .crt containing 
```
-----BEGIN CERTIFICATE-----
... 
-----END CERTIFICATE-----```) via mail, Dropbox, or any other means there and open it. 
iOS will prompt you wether to add this certificate to the key chain.


Subsequent TLS connection to the server identified by the certificate will succeed.

If we are talking about a Client certificate, MQTT-Client-Frameworkd does not support this (yet).

**Comment by ckrey** [comment]
your problem is solved in #34 by @bobwenx

**Comment by Reetalibrarian** [comment]
@ckrey  
Since this post has been post for a while, may I confirm if MQTT-Client still doesn't support client certificate / key yet?

**Comment by ckrey** [comment]
@Reetalibrarian Client Certificates are supported for while now. Please read

http://www.hivemq.com/blog/mqtt-client-library-encyclopedia-mqtt-client-framework

and find a discussion and example with AWS in #120
